// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACcrZCGbL-DjeYQx7itjpd7_Id4LQfapk',
    appId: '1:720073720879:web:78da9af3d78accc6b172da',
    messagingSenderId: '720073720879',
    projectId: 'vox-box-334f6',
    authDomain: 'vox-box-334f6.firebaseapp.com',
    databaseURL: 'https://vox-box-334f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vox-box-334f6.appspot.com',
    measurementId: 'G-41MYS770M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0lLULXC_r1HOTCgWfWXeEImmr9rq7WA',
    appId: '1:720073720879:android:63eef3e4f50c4a43b172da',
    messagingSenderId: '720073720879',
    projectId: 'vox-box-334f6',
    databaseURL: 'https://vox-box-334f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vox-box-334f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGRtMsuCH5Scs4WoHPF9fKutUGUxX6Ls',
    appId: '1:720073720879:ios:daff0f90fa66ebc8b172da',
    messagingSenderId: '720073720879',
    projectId: 'vox-box-334f6',
    databaseURL: 'https://vox-box-334f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vox-box-334f6.appspot.com',
    iosClientId: '720073720879-gs9829kmn6d54dnlighrtro58rm4ibl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkGRtMsuCH5Scs4WoHPF9fKutUGUxX6Ls',
    appId: '1:720073720879:ios:daff0f90fa66ebc8b172da',
    messagingSenderId: '720073720879',
    projectId: 'vox-box-334f6',
    databaseURL: 'https://vox-box-334f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vox-box-334f6.appspot.com',
    iosClientId: '720073720879-gs9829kmn6d54dnlighrtro58rm4ibl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACcrZCGbL-DjeYQx7itjpd7_Id4LQfapk',
    appId: '1:720073720879:web:4e5c06240b0ecdb2b172da',
    messagingSenderId: '720073720879',
    projectId: 'vox-box-334f6',
    authDomain: 'vox-box-334f6.firebaseapp.com',
    databaseURL: 'https://vox-box-334f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vox-box-334f6.appspot.com',
    measurementId: 'G-5TDGB2YYJD',
  );
}
